
services:
  jupyter:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work/notebooks
      - ./data:/home/jovyan/work/data
    container_name: spotify_jupyter
    command: start-notebook.sh --NotebookApp.token=''